import json

from jevbrief import Briefing
from jevbrief.adapters.pr import PrAdapter, parse_diff, role
from jevbrief.testing import FakeJev, check_adapter

DIFF = """diff --git a/src/pay/refund.py b/src/pay/refund.py
index 1111111..2222222 100644
--- a/src/pay/refund.py
+++ b/src/pay/refund.py
@@ -10,6 +10,9 @@ def refund(order, user):
     amount = order.total
-    if user.is_admin:
+    if user.is_admin or user.token == order.token:
+        cursor.execute("UPDATE orders SET refunded = 1 WHERE id = %s" % order.id)
         return amount
+    log.info("refund denied")
     return 0
@@ -40,3 +43,3 @@ class Refunds:
-    def total(self):
+    def  total( self ):
         return sum(self.items)
diff --git a/src/pay/fees.py b/src/pay/fees.py
--- a/src/pay/fees.py
+++ b/src/pay/fees.py
@@ -1,2 +1,3 @@
 RATE = 0.02
+MIN_FEE = 0.3
 CAP = 5
diff --git a/tests/test_fees.py b/tests/test_fees.py
--- a/tests/test_fees.py
+++ b/tests/test_fees.py
@@ -1 +1,2 @@
 from pay.fees import RATE
+from pay.fees import MIN_FEE
diff --git a/package-lock.json b/package-lock.json
--- a/package-lock.json
+++ b/package-lock.json
@@ -1 +1 @@
-{"lockfileVersion": 2}
+{"lockfileVersion": 3}
diff --git a/src/api_pb2.py b/src/api_pb2.py
--- a/src/api_pb2.py
+++ b/src/api_pb2.py
@@ -1 +1 @@
-# old
+# new
diff --git a/vendor/lib/x.go b/vendor/lib/x.go
--- a/vendor/lib/x.go
+++ b/vendor/lib/x.go
@@ -1 +1 @@
-package x
+package x // v2
diff --git a/src/old_name.py b/src/new_name.py
similarity index 100%
rename from src/old_name.py
rename to src/new_name.py
diff --git a/docs/refunds.md b/docs/refunds.md
--- a/docs/refunds.md
+++ b/docs/refunds.md
@@ -1 +1,2 @@
 # Refunds
+Admins can refund any order.
"""


def brief(source, goal="Allow token holders to refund orders", **config):
    b = Briefing(PrAdapter(config), goal, trace=None, jev=FakeJev())
    b.extract(source)
    return b


def by_label(b):
    return {f.label: f for f in b.facts}


def write(tmp_path, name="pr.diff", text=DIFF):
    (tmp_path / name).write_text(text, encoding="utf-8")
    return tmp_path / name


def test_contract(tmp_path):
    check_adapter(PrAdapter(), write(tmp_path), goal="Allow token holders to refund orders")


def test_parse_diff():
    files = {f["path"]: f for f in parse_diff(DIFF)}
    assert len(files) == 8
    refund = files["src/pay/refund.py"]
    assert [(h["new_start"], h["new_len"]) for h in refund["hunks"]] == [(10, 9), (43, 3)]
    assert refund["hunks"][0]["section"] == "def refund(order, user):"
    renamed = files["src/new_name.py"]
    assert renamed["status"] == "renamed" and renamed["old_path"] == "src/old_name.py" and not renamed["hunks"]


def test_roles():
    assert role("src/pay/refund.py") == "source"
    assert role("tests/test_fees.py") == "test" and role("web/cart.spec.ts") == "test"
    assert role("yarn.lock") == "lockfile" and role("api.min.js") == "generated"
    assert role("src/x.py", "# Code generated by protoc. DO NOT EDIT.") == "generated"
    assert role("third_party/zlib/inflate.c") == "vendored"
    assert role("README.md") == "docs" and role(".github/workflows/ci.yml") == "config"


def test_generated(tmp_path):
    b = by_label(brief(write(tmp_path)))
    assert b['package-lock.json:1 {"lockfileVersion": 3}'].reason == "pr.generated"
    assert b["src/api_pb2.py:1 # new"].reason == "pr.generated"


def test_vendored(tmp_path):
    assert by_label(brief(write(tmp_path)))["vendor/lib/x.go:1 package x // v2"].reason == "pr.vendored"


def test_rename_only(tmp_path):
    assert by_label(brief(write(tmp_path)))["src/new_name.py (renamed)"].reason == "pr.rename_only"


def test_formatting_only(tmp_path):
    f = by_label(brief(write(tmp_path)))["src/pay/refund.py:43 class Refunds:"]
    assert not f.kept and f.reason == "pr.formatting_only"


def test_docs_only(tmp_path):
    label = "docs/refunds.md:1 Admins can refund any order."
    assert by_label(brief(write(tmp_path)))[label].kept
    assert by_label(brief(write(tmp_path), drop_docs=True))[label].reason == "pr.docs_only"


def test_risky_area(tmp_path):
    f = by_label(brief(write(tmp_path), goal="pr 12"))["src/pay/refund.py:10 def refund(order, user):"]
    assert f.kept and f.reason == "pr.risky_area"
    assert f.attrs["touches"] == "auth or security, SQL"
    assert f.attrs["matching_test_changed"] == "no" and f.attrs["size"] == "small"


def test_no_test(tmp_path):
    diff = "--- a/src/cart.py\n+++ b/src/cart.py\n@@ -1 +1,2 @@\n x = 1\n+y = 2\n"
    f = brief(diff, goal="pr 12").facts[0]
    assert f.kept and f.reason == "pr.no_test" and f.attrs["change"] == "added"
    b = by_label(brief(write(tmp_path), goal="pr 12"))
    assert b["src/pay/fees.py:1 MIN_FEE = 0.3"].attrs["matching_test_changed"] == "yes"
    assert b["src/pay/fees.py:1 MIN_FEE = 0.3"].reason != "pr.no_test"


PATCH = """From 3f2a Mon Sep 17 00:00:00 2001
From: Dev <dev@example.com>
Subject: [PATCH] Add a minimum fee

--- is not a file header in the message.
---
 src/pay/fees.py | 1 +

diff --git a/src/pay/fees.py b/src/pay/fees.py
--- a/src/pay/fees.py
+++ b/src/pay/fees.py
@@ -1,2 +1,3 @@
 RATE = 0.02
+MIN_FEE = 0.3
 CAP = 5
-- 
2.43.0
"""


def test_patch_file(tmp_path):
    b = brief(write(tmp_path, "0001-fee.patch", PATCH))
    assert [f.label for f in b.facts] == ["src/pay/fees.py:1 MIN_FEE = 0.3"]


def test_api_json_folder(tmp_path):
    files = [{"filename": "src/pay/fees.py", "status": "modified", "changes": 1,
              "patch": "@@ -1,2 +1,3 @@\n RATE = 0.02\n+MIN_FEE = 0.3\n CAP = 5"},
             {"filename": "src/new_name.py", "previous_filename": "src/old_name.py", "status": "renamed",
              "changes": 0},
             {"filename": "logo.png", "status": "added", "changes": 0}]
    (tmp_path / "files.json").write_text(json.dumps(files), encoding="utf-8")
    (tmp_path / "pr.json").write_text(json.dumps({"number": 12, "title": "Add a minimum fee"}), encoding="utf-8")
    b = brief(tmp_path)
    assert b.source["name"] == "Add a minimum fee" and b.source["number"] == 12
    by = by_label(b)
    assert by["src/pay/fees.py:1 MIN_FEE = 0.3"].kept
    assert by["src/new_name.py (renamed)"].reason == "pr.rename_only"
    assert "logo.png (added)" in by


def test_raw_arm_is_the_full_diff(tmp_path):
    a = PrAdapter()
    ex = a.extract(write(tmp_path))
    raw = a.raw(ex.facts)
    assert len(raw) == len(ex.facts)
    assert "+        cursor.execute(" in raw[0].attrs["diff"]


def test_question_pack(tmp_path):
    b = brief(write(tmp_path))
    qs = b.pack.build("g", b.kept, b.state())
    assert set(qs) == {"needs_review", "safe_to_merge"} and qs["safe_to_merge"]["type"] == "noul"
